"""added timestamp to comments table

Revision ID: 143523f70b33
Revises: c6d95635b445
Create Date: 2019-02-18 01:39:55.372608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143523f70b33'
down_revision = 'c6d95635b445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_comment_timestamp'), 'comment', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_timestamp'), table_name='comment')
    op.drop_column('comment', 'timestamp')
    # ### end Alembic commands ###
